tidy

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -7,29 +7,29 @@ alias grep_command="rg --no-messages --color=always --smart-case --line-number"
 
 # Check that dependencies are installed
 function test-cmd-exists() {
-    if ! type $1 > /dev/null; then
-        echo "$fg_bold[red]ERROR$reset_color: $1 not installed. aborting."
+    if ! type "$1" > /dev/null; then
+        echo "${fg_bold[red]}ERROR$reset_color: $1 not installed. aborting."
         exit 1
     fi
 }
 dependencies=(fd fzf sort head nvim git sed tree)
-for d in $dependencies[@]; do test-cmd-exists $d; done
+for d in "${dependencies[@]}"; do test-cmd-exists "$d"; done
 
 # Checks directory is set up
 function check-setup() {
-    if [ ! -d $notes_dir ]; then
+    if [ ! -d "$notes_dir" ]; then
         echo "${fg[blue]}Looks like you don't have a directory at $notes_dir. Making one now...$reset_color"
-        mkdir $notes_dir
+        mkdir "$notes_dir"
     fi
-    cd $notes_dir
+    cd "$notes_dir" || exit
     
-    if [ ! -d $notes_dir/pin ]; then
+    if [ ! -d "$notes_dir/pin" ]; then
         echo "${fg[blue]}Looks like you don't have a directory at $notes_dir/pin. Making one now...$reset_color"
-        mkdir $notes_dir/pin
+        mkdir "$notes_dir/pin"
     fi
     
     
-    if [ ! -d $notes_dir/.git ]; then
+    if [ ! -d "$notes_dir/.git" ]; then
         echo "${fg[blue]}Looks like you haven't set up versioning in $notes_dir. Setting it up now...$reset_color"
         git init &> /dev/null
         git commit --allow-empty -m "init"  &> /dev/null
@@ -39,9 +39,9 @@ check-setup
 
 function get_new_note_name() {
     possible_names=$(printf "new-note-%s\n" {1..1000})
-    for name in ${(@f)possible_names}; do
-        if [ ! -f $name ]; then
-            echo $name
+    for name in "${(@f)possible_names}"; do
+        if [ ! -f "$name" ]; then
+            echo "$name"
             exit 0
         fi
     done
@@ -56,10 +56,10 @@ function sub_help() {
         "grep:Search text of notes"
         "fzf:Fuzzy find note, and open it"
     )
-    echo "notes - bare-bones note management\n"
-    for s in $subcommands; do
+    printf "notes - bare-bones note management\n\n"
+    for s in "${subcommands[@]}"; do
         a=(${(s/:/)s})
-        echo "${a[1]} \t-- ${a[2]}"
+        printf "%s \t-- %s\n" "${a[1]}" "${a[2]}"
     done
 }
 
@@ -71,17 +71,17 @@ function sub_menu() {
     fi
 
     if [[ -d $notes_dir/pin ]]; then
-        pinned=$(fd -t f . $notes_dir/pin -X $stat_command \
+        pinned=$(fd -t f . "$notes_dir/pin" -X "${stat_command[@]}" \
             | sort -r \
             | sed -r 's/^[0-9]+ - (.*)/\1/')
         files=("${(@f)pinned}")
         basenames=("${(@f)$(basename -a $files 2> /dev/null)}")
-        if [[ ${#basenames[@]} > 0 ]]; then
+        if [[ ${#basenames[@]} -gt 0 ]]; then
             echo "${fg_bold[magenta]}Pinned : ${fg_no_bold[magenta]}${basenames[@]}$reset_color"
         fi
     fi
 
-    lines=$(fd -t f . $notes_dir -X $stat_command \
+    lines=$(fd -t f . "$notes_dir" -X "${stat_command[@]}" \
         | sort -r \
         | head -$n_recent_notes \
         | sed -r 's/^[0-9]+ - (.*)/\1/')
@@ -94,21 +94,21 @@ function sub_menu() {
             printf "Name new note (empty for $default_name): $notes_dir/"
             read f
             if [[ $f ]]; then
-                vif $f
+                vif "$f"
             else
-                vif $default_name
+                vif "$default_name"
             fi
         elif [[ $REPLY == 2 ]]; then
             sub_tree
         else
-            vif $files[$REPLY-2]
+            vif "${files[$REPLY-2]}"
         fi
         break
     done
 }
 
 function sub_list() {
-    tree $notes_dir --dirsfirst -C
+    tree "$notes_dir" --dirsfirst -C
 }
 
 function sub_tree() {
@@ -116,7 +116,7 @@ function sub_tree() {
 }
 
 function sub_grep() {
-    grep_command $1 $notes_dir
+    grep_command "$1" "$notes_dir"
 }
 
 function sub_fzf() {
@@ -126,22 +126,22 @@ function sub_fzf() {
 subcommand=$1
 case $subcommand in
     "")
-        sub_menu
+        sub_menu "$@"
         ;;
     "-h" | "--help")
         sub_help
         ;;
     *)
         shift
-        if typeset -f sub_${subcommand} > /dev/null; then 
-            sub_${subcommand} $@
+        if typeset -f "sub_${subcommand}" > /dev/null; then 
+            "sub_${subcommand}" "$@"
             if [ $? = 127 ]; then
-                echo "Not a valid subcommand\n"
+                printf "Not a valid subcommand\n\n"
                 sub_help
                 exit 1
             fi
         else
-            echo "Not a valid subcommand\n"
+            printf "Not a valid subcommand\n\n"
             sub_help
         fi
         ;;
@@ -151,5 +151,5 @@ git add -N .
 git diff --quiet
 if [[ $? ]]; then
     git add .
-    git commit -m $(date '+%y-%m-%d-%H:%M:%S') &> /dev/null
+    git commit -m "$(date '+%y-%m-%d-%H:%M:%S')" &> /dev/null
 fi
